In [ ]:
"""
File: Data Cleaning.ipynb
Author: Abasin Khan
Date: 2026-09-06

Description:
This script demonstrates how to clean and prepare data using Pandas.
It handles missing values, removes inconsistencies, and improves data quality.
"""
import pandas as pd
df = pd.read_excel("pandas_data_cleaning_practice.xlsx")
 
# Always explore data before cleaning it.
df.head()
df.info()
df.shape
df.columns

Index([' Full Name ', 'Age ', ' City', 'Gender', 'Salary', 'Joining Date',
       'Email', ' Unnecessary Column'],
      dtype='str')

In [ ]:
# Checking Missing Values 
df.isnull().sum() # Count Missing Values

 Full Name             1
Age                    2
 City                  1
Gender                 1
Salary                 2
Joining Date           1
Email                  0
 Unnecessary Column    0
dtype: int64

In [ ]:
# Removing Missing Values
df.dropna() # Remove rows containing missing values

In [ ]:
# Filling Missing Values
df["Age "] = df["Age "].fillna(0) # Filling with a Specific Value
df[" City"] = df[" City"].fillna("Unknown")

df = df.fillna(0) # Fill All Missing Values.
df["Age "] = pd.to_numeric(df["Age "], errors="coerce")
df

In [ ]:
# Detecting Duplicate Rows and Removing it
df.duplicated()
df.duplicated().sum() # Counting it
df = df.drop_duplicates() # Removing Duplicate Rows
df

In [ ]:
# Removing Extra spaces

df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower() # Convert to Lower
df.columns = df.columns.str.replace(" ", "_") # Replacing Spaces with Underscores
df

,full_name,age,city,gender,salary,joining_date,email,unnecessary_column
0,Ali Khan,21.0,Lahore,Male,50000,2024-01-15,ali@example.com,remove
1,Sara Ahmed,22.0,karachi,female,0,15/02/2024,sara@example.com,remove
2,Ahmed Raza,0.0,LAHORE,M,45000,invalid,ahmed@example.com,remove
3,ali khan,21.0,Lahore,MALE,50000,2024-01-15,ali@example.com,remove
4,Fatima Noor,-5.0,Islamabad,Female,60000,2023-12-01,fatima@example.com,remove
5,Usman Ali,0.0,Khi,male,55000,2024/03/10,usman@example.com,remove
6,Hina Shah,19.0,peshawar,F,48000,2024-04-20,hina@example.com,remove
7,Bilal Khan,150.0,Lhr,Female,70000,2024-05-05,bilal@example.com,remove
9,NaN,25.0,,M,40000,0,unknown@example.com,remove
10,Zain Malik,30.0,Unknown,Male,unknown,2024-06-01,zain@example.com,remove
11,Maryam Iqbal,0.0,ISLAMABAD,0,65000,2024-13-01,maryam@example.com,remove

In [115]:
# Changing DataTypes
df.dtypes # Checking Data Types
df["age"] = df["age"].astype(int) # Convert to Integer
df["email"] = df["email"].astype(str)
df

,full_name,age,city,gender,salary,joining_date,email,unnecessary_column
0,Ali Khan,21,Lahore,Male,50000,2024-01-15,ali@example.com,remove
1,Sara Ahmed,22,karachi,female,0,15/02/2024,sara@example.com,remove
2,Ahmed Raza,0,LAHORE,M,45000,invalid,ahmed@example.com,remove
3,ali khan,21,Lahore,MALE,50000,2024-01-15,ali@example.com,remove
4,Fatima Noor,-5,Islamabad,Female,60000,2023-12-01,fatima@example.com,remove
5,Usman Ali,0,Khi,male,55000,2024/03/10,usman@example.com,remove
6,Hina Shah,19,peshawar,F,48000,2024-04-20,hina@example.com,remove
7,Bilal Khan,150,Lhr,Female,70000,2024-05-05,bilal@example.com,remove
9,NaN,25,,M,40000,0,unknown@example.com,remove
10,Zain Malik,30,Unknown,Male,unknown,2024-06-01,zain@example.com,remove
11,Maryam Iqbal,0,ISLAMABAD,0,65000,2024-13-01,maryam@example.com,remove

In [127]:
# Working with Dates
df["joining_date"] = pd.to_datetime(
    df["joining_date"],
    errors="coerce"
)
df["joining_date"].isna().sum()  # Check for Missing dates

np.int64(5)

In [ ]:
# Finding Unique Values
df["city"] = df["city"].str.strip().str.title()
df["city"].unique()
df["city"].nunique() # Count Unique Values

<StringArray>
['Lahore', 'Karachi', 'Islamabad', 'Khi', 'Peshawar', 'Lhr', '', 'Unknown']
Length: 8, dtype: str

In [ ]:
# Replacing Incorrect Values
df["gender"] = df["gender"].replace({
    "M": "Male",
    "male": "Male",
    "MALE": "Male"
})

In [144]:
# Removing Invalid Data
df = df[
    (df["age"] >= 0) &
    (df["age"] <= 100)
]

In [ ]:
# Removing Unnecessary Column
df = df.drop(columns=["unnecessary_column"])

,full_name,age,city,gender,salary,joining_date,email
0,Ali Khan,21,Lahore,Male,50000,2024-01-15,ali@example.com
1,Sara Ahmed,22,Karachi,female,0,NaT,sara@example.com
2,Ahmed Raza,0,Lahore,Male,45000,NaT,ahmed@example.com
3,ali khan,21,Lahore,Male,50000,2024-01-15,ali@example.com
5,Usman Ali,0,Khi,Male,55000,NaT,usman@example.com
6,Hina Shah,19,Peshawar,F,48000,2024-04-20,hina@example.com
9,NaN,25,,Male,40000,NaT,unknown@example.com
10,Zain Malik,30,Unknown,Male,unknown,2024-06-01,zain@example.com
11,Maryam Iqbal,0,Islamabad,0,65000,NaT,maryam@example.com

In [146]:
# Reseting Index
df = df.reset_index(drop=True)